# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f15aa0a16041579a97a58441df8527b0f34e1474f55b70882a142b6afe423e937b47bf994efed8d7dce2bf68bc7ff65a6a9057680477e052e5220f592f156272

test:
  secret_key_base: c9b86e9f827e4b5ba15025b1a3b874beae604d5a557755b27167faf0e43b516e3d7d99ff2b76dde1a4409ebb7dde80c77fe093ec56c2e9046259930791b7bc1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
